export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const SET_SUGGESTED_POKEMONS = 'SET_SUGGESTED_POKEMONS';
export const FETCH_POKEMON_PENDING = 'FETCH_POKEMON_PENDING';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_ERROR = 'FETCH_POKEMON_ERROR';
export const SET_FAVORITE = 'SET_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';